services:
  - type: web
    name: femflow-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: FRONTEND_URL
        value: https://femflow-two.vercel.app
