services:
  - type: web
    name: femflow-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        value: noreply@femflow.youcaps.app
      - key: OURA_CLIENT_ID
        sync: false
      - key: OURA_CLIENT_SECRET
        sync: false
      - key: OURA_REDIRECT_URI
        value: https://femflow-api.onrender.com/api/v1/wearable/callback
      - key: FITBIT_CLIENT_ID
        sync: false
      - key: FITBIT_CLIENT_SECRET
        sync: false
      - key: FITBIT_REDIRECT_URI
        value: https://femflow-api.onrender.com/api/v1/wearable/fitbit/callback
      - key: GOOGLE_CLIENT_ID
        value: 301005977940-ik0644unicrshca121j39j8k8tn4qill.apps.googleusercontent.com
      - key: FRONTEND_URL
        value: https://femflow.youcaps.app
